disabled_rules:
 - trailing_whitespace
 - identifier_name
 - force_try
 - force_cast
 - line_length
 - file_length
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
 - Generated
