# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://tdeprez@bitbucket.org/tdeprez/rgpd_pod_spec.git'

target 'plantR_ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for plantR_ios
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Database'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'FirebaseUI/Storage'
  pod 'Firebase/Messaging'

  pod 'SwiftLint'
  pod 'Swinject', '~> 2.6.0'
  pod 'SwinjectStoryboard'
  pod 'SwiftGen'
  pod 'youtube-ios-player-helper'
  # Gestion du clavier
  pod 'IQKeyboardManagerSwift'
  
  # Calendar
  pod 'JTAppleCalendar', '~> 7.1'
  
  pod 'LinearProgressView', '~> 2.0'
  
  pod 'RGPD', '~> 0.0.6'
  pod 'Branch'
  
end
